baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Bloody Gallery'
theme = "hugo-theme-gallery"
ignoreFiles = ["content/barca/.*"]
[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"
[caches]
  [caches.images]
    dir = ':cacheDir/images'
